name: Client

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and deploy application
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      # https://github.com/actions/checkout
      - name: Checkout respository
        uses: actions/checkout@v2

      # https://github.com/actions/setup-node
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          cache: 'npm'
          node-version: ${{ matrix.node }}

      # https://github.com/actions/cache/blob/main/examples.md#node---npm
      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Run linters
        run: npm run lint
