export const locations = [
  {
    category: 'locations.parkly.category',
    coordinates: [60.18108, 24.9786],
    description: 'locations.parkly.description',
    id: '1',
    minDistance: 0.2,
    params: 'parkly',
    title: 'locations.parkly.title',
  },
  {
    category: 'locations.aurora.category',
    coordinates: [60.1806, 24.978],
    description: 'locations.aurora.description',
    id: '2',
    minDistance: 0.2,
    params: 'aurora-block',
    title: 'locations.aurora.title',
  },
  {
    category: 'locations.loviseholm.category',
    coordinates: [60.181, 24.9766],
    description: 'locations.loviseholm.description',
    id: '3',
    minDistance: 0.2,
    params: 'loviseholm-park',
    title: 'locations.loviseholm.title',
  },
  {
    category: 'locations.greenUrbanMapping.category',
    coordinates: [60.1819, 24.9783],
    description: 'locations.greenUrbanMapping.description',
    id: '4',
    minDistance: 0.2,
    params: 'green-urban-mapping',
    title: 'locations.greenUrbanMapping.title',
  },
  {
    category: 'locations.tram.category',
    coordinates: [60.1817, 24.9793],
    description: 'locations.tram.description',
    id: '5',
    minDistance: 0.2,
    params: 'green-tram-stop',
    title: 'locations.tram.title',
  },
];
