export const locations = [
  {
    id: '1',
    title: 'locations.parkly.title',
    category: 'locations.parkly.category',
    description: 'locations.parkly.description',
    coordinates: [60.18108, 24.9786],
    params: 'parkly',
  },
  {
    id: '2',
    title: 'locations.aurora.title',
    coordinates: [60.1806, 24.978],
    category: 'locations.aurora.category',
    description: 'locations.aurora.description',
    params: 'aurora-block',
  },
  {
    id: '3',
    title: 'locations.loviseholm.title',
    coordinates: [60.181, 24.9766],
    category: 'locations.loviseholm.category',
    description: 'locations.loviseholm.description',
    params: 'loviseholm-park',
  },
  {
    id: '4',
    title: 'locations.greenurbanmapping.title',
    coordinates: [60.1819, 24.9783],
    category: 'locations.greenurbanmapping.category',
    description: 'locations.greenurbanmapping.description',
    params: 'green-urban-mapping',
  },
  {
    id: '5',
    title: 'locations.tram.title',
    coordinates: [60.1817, 24.9793],
    category: 'locations.tram.category',
    description: 'locations.tram.description',
    params: 'green-tram-stop',
  },
];
