#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

bold=$(tput bold)
normal=$(tput sgr0)

if env | grep -q SKIP_HUSKY=true; then
  echo "Skipping ${bold}commit-msg${normal} hook …"
else
  npx --no-install commitlint --edit $1
fi
