#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

bold=$(tput bold)
normal=$(tput sgr0)

if env | grep -q SKIP_HUSKY=true; then
  echo "Skipping ${bold}pre-push${normal} hook …"
else
  npm run lint
  npm test
fi
